// SPDX-FileCopyrightText: 2026 Epic Games, Inc.
// SPDX-License-Identifier: MIT
use std::ops::Deref;
use std::sync::Arc;
use std::sync::atomic::AtomicBool;
use std::sync::atomic::Ordering;

use bitflags::bitflags;
use bytes::Bytes;
use bytes::BytesMut;
use lore_error_set::prelude::*;
use parking_lot::RwLock;
use parking_lot::RwLockReadGuard;
use parking_lot::RwLockWriteGuard;
use zerocopy::FromBytes;
use zerocopy::FromZeros;
use zerocopy::Immutable;
use zerocopy::IntoBytes;

use crate::bitflagsops;
use crate::change;
use crate::change::FileAction;
use crate::change::NodeChange;
use crate::errors::InvalidArguments;
use crate::errors::InvalidNodeHierarchy;
use crate::errors::Oversized;
use crate::hash;
use crate::immutable;
use crate::immutable::ImmutableError;
use crate::immutable::ReadBoxFromImmutable;
use crate::lore::Address;
use crate::lore::CloneHeapAlloc;
use crate::lore::Hash;
use crate::lore::RepositoryId;
use crate::lore::ZeroHeapAlloc;
use crate::lore_debug;
use crate::lore_trace;
use crate::node;
use crate::repository::RepositoryContext;
use crate::state::State;
use crate::state::StateError;

/// Identifier of a node within a revision tree.
pub type NodeID = u32;

pub const ROOT_NODE: NodeID = 0;
pub const INVALID_NODE: NodeID = 0xFFFFFFFF;
pub const INVALID_BLOCK: u32 = 0xFFFFFFFF;

pub fn node_to_file_metadata(node: NodeID) -> u32 {
    node
}

pub trait NodeIDExt {
    fn is_valid_node_id(&self) -> bool;
    fn is_valid_or_root_node_id(&self) -> bool;
}

impl NodeIDExt for NodeID {
    fn is_valid_node_id(&self) -> bool {
        *self != ROOT_NODE && *self != INVALID_NODE
    }

    fn is_valid_or_root_node_id(&self) -> bool {
        *self != INVALID_NODE
    }
}

/// Number of bits to shift a full index to get block index
const BLOCK_NODE_SHIFT: u32 = 9;
/// Number of nodes in a block
pub const BLOCK_NODE_COUNT: usize = 512;
/// Bitmask for node index in a full index
const NODE_INDEX_MASK: u32 = (1u32 << BLOCK_NODE_SHIFT) - 1;
/// Maximum size of the per-block node name buffer. Each [`NodeBlock`] holds up
/// to [`BLOCK_NODE_COUNT`] nodes, and the total concatenated name data is
/// capped at this size (4 MiB = ~8 KiB per node, far larger than any
/// legitimate path component). Rejecting further appends prevents a single
/// block from consuming unbounded memory, and bounds the allocation on
/// deserialize.
pub const NODE_NAME_MAX_SIZE: usize = 4 * 1024 * 1024;

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NodeBlockFlags: u32 {
        /// Node block is dirty
        const Dirty = 0b1;
        /// Node block got first block discarded and unused
        const FirstUnusedNode = 0b10;
        /// Name table should be repacked
        const RepackNametable = 0b100;
        /// Defer the name table repack
        const DeferRepackNametable = 0b1000;
        /// Name table was generated by data format upgrade
        const UpgradeGeneratedNametable = 0b10000000000000000;
    }
}
bitflagsops!(NodeBlockFlags, u32);

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
    pub struct NodeFlags: u16 {
        /// No flags
        const NoFlags = 0;

        /// Node is a file, data in node is low 32 bits of modification time
        const File = 0b1;

        /// Node is a link
        const Link = 0b10;

        /// Node have external name string (deprecated)
        const ExternalNameDeprecated = 0b100;

        /// Node has been modified on the filesystem (dirty tracking)
        const Dirty = 0b1000;

        /// Node is staged for commit
        const Staged = 0b10000;

        /// Node is staged for commit by modify
        const StagedModify = 0b110000;

        /// Node is staged for commit by add
        const StagedAdd = 0b1010000;

        /// Node is staged for commit by delete
        const StagedDelete = 0b10010000;

        /// Node is staged for commit by move
        const StagedMove = 0b100010000;

        /// Node is staged for commit by copy
        const StagedCopy = 0b1000010000;

        /// Node is staged for commit by merge
        const StagedMerge = 0b10000010000;

        /// Node is staged for commit by merge with conflict
        const StagedMergeConflict = 0b110000010000;

        /// Node is staged for commit by merge with a resolved conflict
        const StagedMergeResolved = 0b1110000010000;

        /// Node is staged for commit as mine
        const StagedMergeMine = 0b10010000010000;

        /// Node is staged for commit as theirs
        const StagedMergeTheirs = 0b100010000010000;

        /// All staged flags
        const StagedBits = 0b111111111110000;

        /// All staged merge flags
        const StagedMergeBits = 0b111110000010000;

        /// Action bits shared between Dirty and Staged (Modify, Add, Delete, Move, Copy)
        const ActionBits = 0b1111100000;

        /// Merge-related bits (subset of StagedBits, excludes Staged base and ActionBits)
        const MergeBits = 0b111110000000000;

        /// Node is dirty with modify action
        const DirtyModify = 0b101000;

        /// Node is dirty with add action
        const DirtyAdd = 0b1001000;

        /// Node is dirty with delete action
        const DirtyDelete = 0b10001000;

        /// Node is dirty with move action
        const DirtyMove = 0b100001000;

        /// Node is dirty with copy action
        const DirtyCopy = 0b1000001000;

        /// All dirty flags (Dirty base + ActionBits)
        const DirtyBits = 0b1111101000;

        /// Discarded
        const Discarded = 0b1000000000000000;
    }
}
bitflagsops!(NodeFlags, u16);

impl NodeFlags {
    pub fn is_directory(&self) -> bool {
        !(self.contains(NodeFlags::File) || self.contains(NodeFlags::Link))
    }
}

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
    pub struct NodeFlagsV2: u32 {
        /// No flags
        const NoFlags = 0;

        /// Node is a file, data in node is low 32 bits of modification time
        const File = 0b1;

        /// Node is a link
        const Link = 0b10;

        /// Node is a symbolic link
        const SymbolicLink = 0b100;

        /// Executable file
        const Executable = 0b10000;

        /// Discarded
        const Discarded = 0b100000000;

        /// Node has been modified on the filesystem (dirty tracking)
        const Dirty = 0b1000000000000000;

        /// Node is staged for commit
        const Staged = 0b10000000000000000;

        /// Node is staged for commit by modify
        const StagedModify = 0b110000000000000000;

        /// Node is staged for commit by add
        const StagedAdd = 0b1010000000000000000;

        /// Node is staged for commit by delete
        const StagedDelete = 0b10010000000000000000;

        /// Node is staged for commit by move
        const StagedMove = 0b100010000000000000000;

        /// Node is staged for commit by copy
        const StagedCopy = 0b1000010000000000000000;

        /// Node is staged for commit by merge
        const StagedMerge = 0b10000010000000000000000;

        /// Node is staged for commit by merge with conflict
        const StagedMergeConflict = 0b110000010000000000000000;

        /// Node is staged for commit by merge with a resolved conflict
        const StagedMergeResolved = 0b1110000010000000000000000;

        /// Node is staged for commit as mine
        const StagedMergeMine = 0b10010000010000000000000000;

        /// Node is staged for commit as theirs
        const StagedMergeTheirs = 0b100010000010000000000000000;

        /// All staged flags
        const StagedBits = 0b111111111110000000000000000;

        /// All staged merge flags
        const StagedMergeBits = 0b111110000010000000000000000;
    }
}
bitflagsops!(NodeFlagsV2, u32);

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NodeFileMode: u16 {
        /// Node file has no special mode
        const None = 0;
        /// Node file is executable
        const Executable = 0b1;
    }
}
bitflagsops!(NodeFileMode, u16);

/// A node in the revision tree (next data format version), 88 bytes (32 bit index, max 4G nodes)
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, IntoBytes, FromBytes, Immutable)]
pub struct NodeV2 {
    /// Flags
    pub flags: u32,
    /// Directory - first child index
    /// Submodule - Target tree node
    pub child: u32,
    /// Parent index
    pub parent: u32,
    /// Next sibling index
    pub sibling: u32,
    /// Name string offset
    pub name_offset: u32,
    /// Name string length
    pub name_length: u32,
    /// Name hash (case insensitive)
    pub name_hash: u64,
    /// File size
    pub size: u64,
    /// Node content address
    /// - For files this is the content payload (content hash and file ID).
    /// - For directories the hash of all child node content hashes (sorted by node name hash in ascending order).
    /// - For a submodule this is the target revision hash and repository ID.
    pub address: Address,
}

/// A node in the revision tree, 96 bytes (32 bit index, max 4G nodes)
#[repr(C)]
#[derive(Debug, Default, Copy, Clone, IntoBytes, FromBytes, Immutable)]
pub struct Node {
    /// Flags
    pub flags: u16,
    /// File - Executable flag in first bit
    pub mode: u16,
    /// Unused
    pub _unused: u32,
    /// Directory - first child index
    /// Submodule - Target tree node
    pub child: u32,
    /// Parent index
    pub parent: u32,
    /// Next sibling index
    pub sibling: u32,
    /// Name string offset
    pub name_offset: u32,
    /// Name string length
    pub name_length: u32,
    /// Reserved for future use
    pub reserved: u32,
    /// Name hash (case insensitive)
    pub name_hash: u64,
    /// File size
    pub size: u64,
    /// Node content address
    /// - For files this is the content payload (content hash and file ID).
    /// - For directories the hash of all child node content hashes (sorted by node name hash in ascending order).
    /// - For a submodule this is the target revision hash and repository ID.
    pub address: Address,
}

impl Node {
    /// Check if node is staged for inclusion in a commit
    pub fn is_staged(&self) -> bool {
        (self.flags & NodeFlags::Staged) == NodeFlags::Staged.bits()
    }

    /// Check if node is staged for deletion
    pub fn is_staged_delete(&self) -> bool {
        (self.flags & NodeFlags::StagedDelete) == NodeFlags::StagedDelete.bits()
    }

    /// Check if node is staged for add
    pub fn is_staged_add(&self) -> bool {
        (self.flags & NodeFlags::StagedAdd) == NodeFlags::StagedAdd.bits()
    }

    /// Check if node is staged for modify
    pub fn is_staged_modify(&self) -> bool {
        (self.flags & NodeFlags::StagedModify) == NodeFlags::StagedModify.bits()
    }

    /// Check if node is staged for move
    pub fn is_staged_move(&self) -> bool {
        (self.flags & NodeFlags::StagedMove) == NodeFlags::StagedMove.bits()
    }

    /// Check if node is staged for copy
    pub fn is_staged_copy(&self) -> bool {
        (self.flags & NodeFlags::StagedCopy) == NodeFlags::StagedCopy.bits()
    }

    /// Check if node is part of a merge
    pub fn is_staged_merge(&self) -> bool {
        (self.flags & NodeFlags::StagedMerge) == NodeFlags::StagedMerge.bits()
    }

    /// Check if node is part of a conflict - either resolved or unresolved
    pub fn is_staged_merge_conflict(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeConflict) == NodeFlags::StagedMergeConflict.bits()
    }

    /// Check if node is part of a conflict - resolved
    pub fn is_staged_merge_resolved(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeResolved) == NodeFlags::StagedMergeResolved.bits()
    }

    /// Check if node is part of a conflict - unresolved
    pub fn is_staged_merge_unresolved(&self) -> bool {
        self.is_staged_merge_conflict() && !self.is_staged_merge_resolved()
    }

    /// Check if node is part of a conflict and the mine version got staged
    pub fn is_staged_merge_mine(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeMine) == NodeFlags::StagedMergeMine.bits()
    }

    /// Check if node is part of a conflict and the theirs version got staged
    pub fn is_staged_merge_theirs(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeTheirs) == NodeFlags::StagedMergeTheirs.bits()
    }

    /// Check if the node is a file
    pub fn is_file(&self) -> bool {
        (self.flags & NodeFlags::File) == NodeFlags::File.bits()
    }

    /// Check if the node is a link
    pub fn is_link(&self) -> bool {
        (self.flags & NodeFlags::Link) == NodeFlags::Link.bits()
    }

    /// Check if the node is a directory
    pub fn is_directory(&self) -> bool {
        !self.is_file() && !self.is_link()
    }

    /// Check if node is marked as discarded
    pub fn is_discarded(&self) -> bool {
        (self.flags & NodeFlags::Discarded) == NodeFlags::Discarded.bits()
    }

    /// Check if node is dirty (filesystem change detected)
    pub fn is_dirty(&self) -> bool {
        (self.flags & NodeFlags::Dirty) == NodeFlags::Dirty.bits()
    }

    /// Check if node is dirty with modify action
    pub fn is_dirty_modify(&self) -> bool {
        (self.flags & NodeFlags::DirtyModify) == NodeFlags::DirtyModify.bits()
    }

    /// Check if node is dirty with add action
    pub fn is_dirty_add(&self) -> bool {
        (self.flags & NodeFlags::DirtyAdd) == NodeFlags::DirtyAdd.bits()
    }

    /// Check if node is dirty with delete action
    pub fn is_dirty_delete(&self) -> bool {
        (self.flags & NodeFlags::DirtyDelete) == NodeFlags::DirtyDelete.bits()
    }

    /// Check if node is dirty with move action
    pub fn is_dirty_move(&self) -> bool {
        (self.flags & NodeFlags::DirtyMove) == NodeFlags::DirtyMove.bits()
    }

    /// Check if node is dirty with copy action
    pub fn is_dirty_copy(&self) -> bool {
        (self.flags & NodeFlags::DirtyCopy) == NodeFlags::DirtyCopy.bits()
    }

    /// Check if node is dirty or staged (has any lifecycle change)
    pub fn is_dirty_or_staged(&self) -> bool {
        self.is_dirty() || self.is_staged()
    }

    /// Check if node has any change flags (`Dirty`, `Staged`, or `ActionBits`)
    pub fn has_any_change_flags(&self) -> bool {
        (self.flags & (NodeFlags::Dirty.bits() | NodeFlags::StagedBits.bits())) != 0
    }

    /// Extract just the action bits (bits 5-9) from the node flags
    pub fn action_bits(&self) -> u16 {
        self.flags & NodeFlags::ActionBits.bits()
    }

    /// Clear staged flags. Preserves `Dirty` and action bits if `Dirty` is set.
    /// Clears `Staged` (bit 4) + `MergeBits` (10-14). Clears `ActionBits` only if `Dirty` is not set.
    pub fn clear_staged_flags(&mut self) {
        let has_dirty = self.is_dirty();
        self.flags &= !(NodeFlags::Staged.bits() | NodeFlags::MergeBits.bits());
        if !has_dirty {
            self.flags &= !NodeFlags::ActionBits.bits();
        }
    }

    /// Clear dirty flags. Preserves `Staged` and action bits if `Staged` is set.
    /// Clears `Dirty` (bit 3). Clears `ActionBits` only if `Staged` is not set.
    pub fn clear_dirty_flags(&mut self) {
        let has_staged = self.is_staged();
        self.flags &= !NodeFlags::Dirty.bits();
        if !has_staged {
            self.flags &= !NodeFlags::ActionBits.bits();
        }
    }

    /// Clear all change flags (`Dirty` + `Staged` + `ActionBits` + `MergeBits`). Preserves type flags.
    pub fn clear_all_change_flags(&mut self) {
        self.flags &= !(NodeFlags::Dirty.bits() | NodeFlags::StagedBits.bits());
    }

    const fn index_clamp(index: u32) -> u32 {
        if index < BLOCK_NODE_COUNT as u32 {
            index
        } else {
            0
        }
    }

    /// Get the node index from a full node ID
    pub fn index(node: NodeID) -> usize {
        Self::index_clamp(node & NODE_INDEX_MASK) as usize
    }

    /// Get the first child node (only for directory nodes)
    pub fn child(&self) -> Option<NodeID> {
        debug_assert!(self.is_directory());
        let node = self.child as NodeID;
        if node.is_valid_node_id() {
            Some(node)
        } else {
            None
        }
    }

    /// Get the sibling of this node
    pub fn sibling(&self) -> Option<NodeID> {
        let node = self.sibling as NodeID;
        if node.is_valid_node_id() {
            Some(node)
        } else {
            None
        }
    }

    /// Get submodule node link (only for module nodes)
    pub fn linked_node(&self) -> NodeLink {
        debug_assert!(self.is_link());
        NodeLink {
            node: self.child,
            repository: self.address.context.into(),
            revision: self.address.hash,
        }
    }

    /// Verify that this node, reached as a child of `expected_parent` during a
    /// tree walk, has its parent pointer matching. Detects cycles (a child
    /// pointer leading to an ancestor) and diamonds (a node referenced as a
    /// child by more than one parent). Should be invoked on every child the
    /// walk descends into and on every sibling along the chain.
    ///
    /// Returns a [`StateError`](crate::state::StateError) wrapping
    /// `InvalidNodeHierarchy` so callers can use `?` directly when they
    /// already work with `StateError`, or `.forward::<TargetError>(..)` to
    /// re-emit under another error set.
    pub fn check_parent_link(
        &self,
        node_id: NodeID,
        expected_parent: NodeID,
    ) -> Result<(), crate::state::StateError> {
        if self.parent != expected_parent {
            return Err(crate::state::StateError::from(InvalidNodeHierarchy {
                node: node_id,
                expected_parent,
                actual_parent: self.parent,
            }));
        }
        Ok(())
    }

    /// Combined per-step check for tree walks over a directory's sibling chain.
    /// Validates the parent back-pointer via [`Self::check_parent_link`] *and*
    /// records the visit with `cycle` to catch sibling cycles where every node
    /// has a legal parent pointer but the sibling links loop back on themselves
    /// (which the parent check alone cannot detect). Call once per node
    /// visited, including the first child.
    pub fn walk_step(
        &self,
        node_id: NodeID,
        expected_parent: NodeID,
        cycle: &mut SiblingCycleGuard,
    ) -> Result<(), crate::state::StateError> {
        self.check_parent_link(node_id, expected_parent)?;
        cycle
            .observe(node_id)
            .map_err(crate::state::StateError::from)?;
        Ok(())
    }
}

/// Allocation-free cycle detector for walking a directory's singly-linked
/// sibling chain (`Node::child` → `Node::sibling` → `Node::sibling` → …).
///
/// # Why it is needed
///
/// [`Node::check_parent_link`] catches cycles that reroute through a node
/// with a *different* parent pointer (the common shape of a tree-corruption
/// bug), but it cannot detect cycles where every node in the chain still
/// carries the correct parent ID — e.g. `P.child = A`, `A.sibling = B`,
/// `B.sibling = A`, all three with `parent = P`. The parent check is happy
/// and a naive walk loops forever.
///
/// # Algorithm
///
/// Brent's cycle-detection algorithm. We keep a single *snapshot* node and a
/// window length that doubles each time it expires:
///
/// * On every visit we compare the current node ID against the snapshot — if
///   they match, the chain has revisited a node, which is a cycle.
/// * Every `window` steps we advance the snapshot to the current node and
///   double `window`. So snapshots are taken at indices `2^k − 1` (1, 3, 7,
///   15, 31, …) and each remains active for `2^k` observations.
///
/// State is sixteen bytes (one `NodeID`, one `Option<NodeID>`, two `u32`s)
/// and stays on the stack — no heap allocation per iteration site.
///
/// # Proof that every cycle is caught
///
/// Let the chain be `x₀, x₁, …`. If it enters a cycle there exist unique
/// `μ ≥ 0` (tail length) and `λ ≥ 1` (cycle length) with `x_{μ+λ} = x_μ` and
/// `x_{i+λ} = x_i` for all `i ≥ μ`. Choose the smallest `k` with `2^k ≥ μ+λ`
/// and let `n = 2^k − 1`. Then:
///
/// 1. `n ≥ μ + λ − 1 ≥ μ`, so the snapshot `x_n` lies inside the cycle.
/// 2. The snapshot is active for the next `2^k = n + 1 ≥ λ + 1` observations
///    — i.e. throughout steps `n+1 .. 2n+1`.
/// 3. By cycle periodicity `x_{n+λ} = x_n`, and `n + λ ∈ [n+1, 2n+1]` because
///    `λ ≤ 2^k`. So observation `n + λ` matches the active snapshot and the
///    guard returns an error.
///
/// Equality of `NodeID`s implies identity, so the check has no false
/// positives.
///
/// # Worst-case iteration count
///
/// Detection occurs at step `n + λ ≤ 3(μ + λ) − 2`, i.e. *O(μ + λ)* —
/// linear in the chain length, with a worst-case constant of `~3×`
/// (hit when `μ + λ` is just above a power of two). On a clean chain of
/// length `N` the guard adds one `NodeID` compare and one `u32` increment
/// per step and never returns an error. For `N = 2^16` the worst case is
/// under `196 608` observations.
#[derive(Debug, Clone, Copy)]
pub struct SiblingCycleGuard {
    /// Parent whose child/sibling chain is being walked.
    parent_node_id: NodeID,
    /// Most recent snapshot — every observation is compared against this.
    snapshot: Option<NodeID>,
    /// Observations since the last snapshot was taken.
    steps: u32,
    /// Snapshot window length; doubles each time it expires.
    window: u32,
}

impl SiblingCycleGuard {
    pub const fn new(parent_node_id: NodeID) -> Self {
        Self {
            parent_node_id,
            snapshot: None,
            steps: 0,
            window: 1,
        }
    }

    /// Record an observation of `node_id` as the next visited node in the
    /// chain. Returns `InvalidNodeHierarchy` if `node_id` matches the active
    /// snapshot, signalling a sibling-chain cycle.
    pub fn observe(&mut self, node_id: NodeID) -> Result<(), InvalidNodeHierarchy> {
        if self.snapshot == Some(node_id) {
            return Err(InvalidNodeHierarchy {
                node: node_id,
                expected_parent: self.parent_node_id,
                actual_parent: node_id,
            });
        }
        if self.steps == self.window {
            self.snapshot = Some(node_id);
            self.steps = 0;
            self.window = self.window.saturating_mul(2);
        }
        self.steps += 1;
        Ok(())
    }
}

#[cfg(test)]
mod cycle_tests {
    use super::*;

    #[test]
    fn clean_chain_passes() {
        let mut guard = SiblingCycleGuard::new(1);
        for id in 2..1000 {
            guard.observe(id).expect("clean chain should not trip");
        }
    }

    #[test]
    fn self_loop_at_head_detected() {
        // A.sibling = A, walked as A, A, A, ...
        let mut guard = SiblingCycleGuard::new(1);
        guard.observe(42).unwrap();
        guard.observe(42).unwrap();
        let err = guard.observe(42).expect_err("self loop must trip");
        assert_eq!(err.node, 42);
        assert_eq!(err.expected_parent, 1);
        assert_eq!(err.actual_parent, 42);
    }

    #[test]
    fn two_cycle_detected() {
        // A -> B -> A -> B -> ...
        let mut guard = SiblingCycleGuard::new(1);
        guard.observe(10).unwrap();
        guard.observe(20).unwrap();
        guard.observe(10).unwrap();
        guard.observe(20).expect_err("two-cycle must trip");
    }

    #[test]
    fn three_cycle_detected() {
        // A -> B -> C -> A -> B -> C -> A ...
        let chain = [10u32, 20, 30, 10, 20, 30, 10];
        let mut guard = SiblingCycleGuard::new(1);
        let mut tripped_at = None;
        for (i, id) in chain.iter().enumerate() {
            if guard.observe(*id).is_err() {
                tripped_at = Some(i);
                break;
            }
        }
        let i = tripped_at.expect("three-cycle must trip");
        assert!(i <= 6, "expected detection within 7 steps, got step {i}");
    }

    #[test]
    fn mid_chain_cycle_detected() {
        // A -> B -> C -> D -> E -> F -> G -> D -> E -> F -> G -> D ...
        let mut chain = vec![10u32, 20, 30, 40, 50, 60, 70];
        for _ in 0..20 {
            chain.extend_from_slice(&[40, 50, 60, 70]);
        }
        let mut guard = SiblingCycleGuard::new(1);
        let mut tripped = false;
        for id in &chain {
            if guard.observe(*id).is_err() {
                tripped = true;
                break;
            }
        }
        assert!(tripped, "mid-chain cycle must trip");
    }

    #[test]
    fn worst_case_bound_holds_for_small_cycles() {
        // For chain length N ≤ 2^k, detection step ≤ 3N.
        // Try several cycle sizes and verify the bound.
        for cycle_len in [1u32, 2, 3, 5, 8, 10, 13, 64, 256] {
            let mut guard = SiblingCycleGuard::new(1);
            let mut steps = 0u32;
            loop {
                let id = 100 + (steps % cycle_len);
                steps += 1;
                if guard.observe(id).is_err() {
                    break;
                }
                assert!(
                    steps < 3 * cycle_len.max(1) + 10,
                    "cycle_len={cycle_len} took {steps} steps, exceeds bound",
                );
            }
        }
    }
}

/// Block format version identifiers
#[repr(u32)]
pub enum NodeBlockFormat {
    /// Initial version
    Initial = 0,
    /// Name table per block
    Nametable = 1,
    /// No timestamp
    NoTimestamp = 2,
}

/// A block of nodes, 49280 bytes - 128 byte metadata, 512 nodes (96 bytes each)
#[repr(C)]
#[derive(Clone, IntoBytes, FromBytes, Immutable)]
pub struct NodeBlockData {
    /// Block flags
    pub flags: u32,
    /// Number of initialized nodes
    pub node_count: u32,
    /// Number of unused nodes
    pub node_unused_count: u32,
    /// First unused node index
    pub node_unused: u32,
    /// Next block with unused slots
    pub block_unused_next: u32,
    /// Block data format version
    pub version: u32,
    /// Reserved for future extensions, must be zero
    reserved: [u32; 2],
    /// Name table address
    pub name_table: Hash,
    /// Reserved for future extensions, must be zero
    reserved_hash: [Hash; 2],
    /// Node data
    pub node: [Node; BLOCK_NODE_COUNT],
}

impl ReadBoxFromImmutable for NodeBlockData {}
impl ZeroHeapAlloc for NodeBlockData {}
impl CloneHeapAlloc for NodeBlockData {}

/// A block of nodes, 45184 bytes - 128 byte metadata, 512 nodes (96 bytes each)
#[repr(C)]
#[derive(Clone, IntoBytes, FromBytes, Immutable)]
pub struct NodeBlockDataV2 {
    /// Block flags
    pub flags: u32,
    /// Number of initialized nodes
    pub node_count: u32,
    /// Number of unused nodes
    pub node_unused_count: u32,
    /// First unused node index
    pub node_unused: u32,
    /// Next block with unused slots
    pub block_unused_next: u32,
    /// Block data format version
    pub version: u32,
    /// Reserved for future extensions, must be zero
    reserved: [u32; 2],
    /// Name table address
    pub name_table: Hash,
    /// Reserved for future extensions, must be zero
    reserved_hash: [Hash; 2],
    /// Node data
    pub node: [NodeV2; BLOCK_NODE_COUNT],
}

impl ReadBoxFromImmutable for NodeBlockDataV2 {}
impl ZeroHeapAlloc for NodeBlockDataV2 {}
impl CloneHeapAlloc for NodeBlockDataV2 {}

/// Limit of inline name string in data format version 0
pub const NODE_NAME_LIMIT: usize = 43;
/// Number of nodes in a block in version 0
pub const BLOCK_V0_NODE_COUNT: usize = 511;

#[repr(C)]
#[derive(Clone, IntoBytes, FromBytes, Immutable)]
pub struct NodeBlockDataV0 {
    /// Block flags
    pub flags: u32,
    /// Number of initialized nodes
    pub node_count: u32,
    /// Number of unused nodes
    pub node_unused_count: u32,
    /// First unused node index
    pub node_unused: u32,
    /// Next block with unused slots
    pub block_unused_next: u32,
    /// Reserved for future extensions, must be zero
    reserved: [u32; 3],
    /// Node data
    pub node: [NodeV0; BLOCK_V0_NODE_COUNT],
}

impl ReadBoxFromImmutable for NodeBlockDataV0 {}
impl ZeroHeapAlloc for NodeBlockDataV0 {}
impl CloneHeapAlloc for NodeBlockDataV0 {}

/// A node in the revision tree, 128 bytes (32 bit index, max 4G nodes)
#[repr(C)]
#[derive(Debug, Copy, Clone, IntoBytes, FromBytes, Immutable)]
pub struct NodeV0 {
    /// Flags
    pub flags: u16,
    /// File - Executable flag in first bit
    pub mode: u16,
    /// File - Last modified time high 16 bits
    pub mtime_high: u32,
    /// Directory - first child index
    /// File - Last modified time
    /// Submodule - Target tree node
    pub child_mtime_node: u32,
    /// Parent index
    pub parent: u32,
    /// Next sibling index
    pub sibling: u32,
    /// Name string (last byte is length)
    pub name_string: [u8; NODE_NAME_LIMIT + 1],
    /// Name hash (case insensitive)
    pub name_hash: u64,
    /// File size
    pub size: u64,
    /// Node content address
    /// - For files this is the content payload (content hash and file ID).
    /// - For directories the hash of all child node content hashes (sorted by node name hash in ascending order).
    /// - For a submodule this is the target revision hash and repository ID.
    pub address: Address,
}

impl NodeV0 {
    /// Check if node is staged for inclusion in a commit
    pub fn is_staged(&self) -> bool {
        (self.flags & NodeFlags::Staged) == NodeFlags::Staged.bits()
    }

    /// Check if node is staged for deletion
    pub fn is_staged_delete(&self) -> bool {
        (self.flags & NodeFlags::StagedDelete) == NodeFlags::StagedDelete.bits()
    }

    /// Check if node is staged for add
    pub fn is_staged_add(&self) -> bool {
        (self.flags & NodeFlags::StagedAdd) == NodeFlags::StagedAdd.bits()
    }

    /// Check if node is staged for modify
    pub fn is_staged_modify(&self) -> bool {
        (self.flags & NodeFlags::StagedModify) == NodeFlags::StagedModify.bits()
    }

    /// Check if node is staged for move
    pub fn is_staged_move(&self) -> bool {
        (self.flags & NodeFlags::StagedMove) == NodeFlags::StagedMove.bits()
    }

    /// Check if node is staged for copy
    pub fn is_staged_copy(&self) -> bool {
        (self.flags & NodeFlags::StagedCopy) == NodeFlags::StagedCopy.bits()
    }

    /// Check if node is part of a merge
    pub fn is_staged_merge(&self) -> bool {
        (self.flags & NodeFlags::StagedMerge) == NodeFlags::StagedMerge.bits()
    }

    /// Check if node is part of a conflict - either resolved or unresolved
    pub fn is_staged_merge_conflict(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeConflict) == NodeFlags::StagedMergeConflict.bits()
    }

    /// Check if node is part of a conflict - resolved
    pub fn is_staged_merge_resolved(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeResolved) == NodeFlags::StagedMergeResolved.bits()
    }

    /// Check if node is part of a conflict - unresolved
    pub fn is_staged_merge_unresolved(&self) -> bool {
        self.is_staged_merge_conflict() && !self.is_staged_merge_resolved()
    }

    /// Check if node is part of a conflict and the mine version got staged
    pub fn is_staged_merge_mine(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeMine) == NodeFlags::StagedMergeMine.bits()
    }

    /// Check if node is part of a conflict and the theirs version got staged
    pub fn is_staged_merge_theirs(&self) -> bool {
        (self.flags & NodeFlags::StagedMergeTheirs) == NodeFlags::StagedMergeTheirs.bits()
    }

    /// Check if the node is a file
    pub fn is_file(&self) -> bool {
        (self.flags & NodeFlags::File) == NodeFlags::File.bits()
    }

    /// Check if the node is a link
    pub fn is_link(&self) -> bool {
        (self.flags & NodeFlags::Link) == NodeFlags::Link.bits()
    }

    /// Check if the node is a directory
    pub fn is_directory(&self) -> bool {
        !self.is_file() && !self.is_link()
    }

    /// Check if node is marked as discarded
    pub fn is_discarded(&self) -> bool {
        (self.flags & NodeFlags::Discarded) == NodeFlags::Discarded.bits()
    }

    /// Check if the node has an external name string
    pub fn has_external_name(&self) -> bool {
        NodeFlags::from_bits_retain(self.flags).contains(NodeFlags::ExternalNameDeprecated)
    }

    const fn index_clamp(index: u32) -> u32 {
        if index < BLOCK_NODE_COUNT as u32 {
            index
        } else {
            0
        }
    }

    /// Get the node index from a full node ID
    pub fn index(node: NodeID) -> usize {
        Self::index_clamp(node & NODE_INDEX_MASK) as usize
    }

    /// Get the first child node (only for directory nodes)
    pub fn child(&self) -> Option<NodeID> {
        debug_assert!(self.is_directory());
        let node = self.child_mtime_node as NodeID;
        if node.is_valid_node_id() {
            Some(node)
        } else {
            None
        }
    }

    /// Get the sibling of this node
    pub fn sibling(&self) -> Option<NodeID> {
        let node = self.sibling as NodeID;
        if node.is_valid_node_id() {
            Some(node)
        } else {
            None
        }
    }

    /// Get the last modified time (only for file nodes)
    pub fn mtime(&self) -> u64 {
        debug_assert!(self.is_file());
        ((self.mtime_high as u64) << 32u64) | (self.child_mtime_node as u64)
    }

    /// Get submodule node link (only for module nodes)
    pub fn linked_node(&self) -> NodeLink {
        debug_assert!(self.is_link());
        NodeLink {
            node: self.child_mtime_node,
            repository: self.address.context.into(),
            revision: self.address.hash,
        }
    }
}

struct NodeBlockRuntimeData {
    data: Box<NodeBlockData>,
    name: BytesMut,
}

/// Internally mutable wrapper around a block of nodes
pub struct NodeBlock {
    /// First element is node block data containing all the nodes,
    /// second element is name table buffer
    data: Arc<parking_lot::RwLock<NodeBlockRuntimeData>>,
    /// Flag indicating name table has been deserialized
    name_deserialized: AtomicBool,
}

/// Read accessor for a node block
pub struct NodeBlockReader<'a> {
    lock: RwLockReadGuard<'a, NodeBlockRuntimeData>,
}

/// Write accessor for a node block
pub struct NodeBlockWriter<'a> {
    lock: RwLockWriteGuard<'a, NodeBlockRuntimeData>,
}

#[error_set]
pub enum NodeNameError {
    InvalidArguments,
    Oversized,
}

fn validate_node_name(name: &str) -> Result<(), NodeNameError> {
    if name == ".." || name.starts_with('\0') || name.bytes().any(|b| b == b'/' || b == b'\\') {
        return Err(InvalidArguments {
            reason: format!("invalid node name: {name}"),
        }
        .into());
    }
    Ok(())
}

/// Owned node name backed by an arc read lock on the containing node block.
/// Since this holds a read lock on the node block, make sure to drop it as soon as possible.
/// Dereferences to `&str` for zero-copy name access. This type is `Send`
/// because it uses an `ArcRwLockReadGuard` rather than a borrowed guard.
pub struct NodeNameLock {
    // Safety invariant: `name` points into `guard.name[offset..offset+len]` and is
    // kept valid by the guard holding the arc read lock on the block data.
    // The guard must be declared after `name` so it is dropped last.
    name: *const str,
    _guard: parking_lot::ArcRwLockReadGuard<parking_lot::RawRwLock, NodeBlockRuntimeData>,
}

impl NodeNameLock {
    pub fn freeze(self) -> String {
        self.deref().to_string()
    }
}

impl AsRef<str> for NodeNameLock {
    fn as_ref(&self) -> &str {
        self
    }
}

impl AsRef<std::path::Path> for NodeNameLock {
    fn as_ref(&self) -> &std::path::Path {
        std::path::Path::new(&**self)
    }
}

impl std::ops::Deref for NodeNameLock {
    type Target = str;
    fn deref(&self) -> &str {
        // SAFETY: `name` is a valid pointer into the guard's name table,
        // which is kept alive by `_guard`.
        unsafe { &*self.name }
    }
}

impl std::fmt::Display for NodeNameLock {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self)
    }
}

// SAFETY: NodeNameLock contains a *const str pointing into the ArcRwLockReadGuard's
// name table buffer. The guard keeps the data alive and prevents writers. The raw
// pointer is !Send by default, but moving NodeNameLock between threads is safe because
// the ArcRwLockReadGuard owns an Arc reference to the block, ensuring the pointed-to
// data remains valid. The !Sync BytesMut is only read through the pointer, never
// modified, dropped, or cloned.
unsafe impl Send for NodeNameLock {}

impl NodeBlock {
    pub fn new(data: Box<NodeBlockData>) -> Self {
        NodeBlock {
            data: Arc::new(RwLock::new(NodeBlockRuntimeData {
                data,
                name: BytesMut::new(),
            })),
            name_deserialized: AtomicBool::new(false),
        }
    }

    pub fn new_with_name(data: Box<NodeBlockData>, name: BytesMut) -> Self {
        NodeBlock {
            data: Arc::new(RwLock::new(NodeBlockRuntimeData { data, name })),
            name_deserialized: AtomicBool::new(true),
        }
    }

    pub fn new_zeroed() -> Self {
        let mut data = NodeBlockData::new_from_heap_zeroed();
        data.block_unused_next = INVALID_BLOCK;
        data.version = NodeBlockFormat::Nametable as u32;
        Self::new_with_name(data, BytesMut::new())
    }

    /// Get the block index from a full node ID
    pub fn index(node: NodeID) -> usize {
        (node >> BLOCK_NODE_SHIFT) as usize
    }

    /// Acquire read access to the node block
    pub fn read(&self) -> NodeBlockReader<'_> {
        NodeBlockReader {
            lock: self.data.read(),
        }
    }

    /// Acquire write access to the node block
    pub fn write(&self) -> NodeBlockWriter<'_> {
        NodeBlockWriter {
            lock: self.data.write(),
        }
    }

    /// Read only node access without keeping lock, data returned by copy
    pub fn node(&self, node_index: usize) -> Node {
        *self.read().node(node_index)
    }

    /// Read only node access without keeping lock, data returned by clone
    pub fn node_name_clone(&self, node_index: usize) -> Result<String, NodeNameError> {
        let guard = self.data.read();
        let node = &guard.data.node[node_index];
        let offset = node.name_offset as usize;
        let length = node.name_length as usize;
        if guard.name.len() < (offset + length) {
            return Err(InvalidArguments {
                reason: format!(
                    "node name offset {offset} + length {length} exceeds name table size {}",
                    guard.name.len()
                ),
            }
            .into());
        }
        let name =
            std::str::from_utf8(&guard.name[offset..(offset + length)]).internal("Node name")?;
        validate_node_name(name)?;
        Ok(name.to_string())
    }

    /// Returns the node name as a lock guard that holds a read lock on the block data.
    /// The returned `NodeNameLock` keeps the `RwLock` read guard alive for its lifetime.
    /// Callers must drop the returned value before calling `write()` on the same block,
    /// or the write lock acquisition will deadlock.
    pub fn node_name_ref(&self, node_index: usize) -> Result<NodeNameLock, NodeNameError> {
        let guard = self.data.read_arc();
        let node = &guard.data.node[node_index];
        let offset = node.name_offset as usize;
        let length = node.name_length as usize;
        if guard.name.len() < (offset + length) {
            return Err(InvalidArguments {
                reason: format!(
                    "node name offset {offset} + length {length} exceeds name table size {}",
                    guard.name.len()
                ),
            }
            .into());
        }
        let name_str =
            std::str::from_utf8(&guard.name[offset..(offset + length)]).internal("Node name")?;
        validate_node_name(name_str)?;
        let name: *const str = name_str;
        Ok(NodeNameLock {
            name,
            _guard: guard,
        })
    }

    pub async fn deserialize_nametable(
        &self,
        repository: Arc<RepositoryContext>,
    ) -> Result<(), StateError> {
        if self.is_nametable_deserialized() {
            return Ok(());
        }

        Box::pin(async move { self.deserialize_nametable_impl(repository).await }).await
    }

    async fn deserialize_nametable_impl(
        &self,
        repository: Arc<RepositoryContext>,
    ) -> Result<(), StateError> {
        let name_table = { self.read().lock.data.name_table };

        // Deserialize name table
        let bytes = immutable::read(
            repository.clone(),
            Address::zero_context_hash(name_table),
            None,
            immutable::read_options_from_repository(&repository)
                .with_cache()
                .with_priority()
                .with_max_content_size(NODE_NAME_MAX_SIZE as u64),
        )
        .await
        .internal("Deserialize deprecated name table failed")?;

        let nametable = bytes
            .try_into_mut()
            .unwrap_or_else(|bytes| BytesMut::from(&bytes[..]));

        let mut writer = self.write();
        if !self.is_nametable_deserialized() {
            writer.lock.name = nametable;
            self.name_deserialized.store(true, Ordering::Relaxed);
        }

        Ok(())
    }

    pub fn is_nametable_deserialized(&self) -> bool {
        self.name_deserialized.load(Ordering::Relaxed)
    }

    pub fn node_name_repack(&self) {
        let mut lock = self.write();
        lock.node_name_repack();
    }

    pub async fn deserialize(
        repository: Arc<RepositoryContext>,
        state: &State,
        address: Address,
    ) -> Result<NodeBlock, StateError> {
        // Normal path, expect latest data format version
        if let Ok(mut block_data) =
            NodeBlockData::read_box_from_immutable(repository.clone(), address, true).await
        {
            if block_data.version > NodeBlockFormat::Nametable as u32 {
                return Err(StateError::internal(format!(
                    "New revision state node block format encountered, please update your urc client: version {}",
                    block_data.version
                )));
            }
            block_data.flags &= !NodeBlockFlags::Dirty;
            block_data.flags &= !NodeBlockFlags::DeferRepackNametable;
            Ok(NodeBlock::new(block_data))
        } else {
            Self::deserialize_other_version(repository, state, address).await
        }
    }

    pub async fn deserialize_other_version(
        repository: Arc<RepositoryContext>,
        state: &State,
        address: Address,
    ) -> Result<NodeBlock, StateError> {
        // Try load old data format
        if let Ok(block_data_v0) =
            NodeBlockDataV0::read_box_from_immutable(repository.clone(), address, true).await
        {
            lore_trace!("Converting v0 block data format when deserializing block");
            let (mut block_data, name) =
                Self::convert_block_v0(repository.clone(), state, block_data_v0).await?;

            block_data.flags &= !NodeBlockFlags::Dirty;
            block_data.flags &= !NodeBlockFlags::DeferRepackNametable;

            return Ok(NodeBlock::new_with_name(block_data, name));
        };

        let block_data_v2 =
            match NodeBlockDataV2::read_box_from_immutable(repository.clone(), address, true).await
            {
                Ok(data) => Ok(data),
                Err(err) => Err(err)
                    .internal("Deserialize node block failed")
                    .map_err(StateError::from),
            }?;

        lore_debug!("Converting v2 block data format when deserializing block");
        let mut block_data = Self::convert_block_v2(repository.clone(), block_data_v2)?;

        block_data.flags &= !NodeBlockFlags::Dirty;
        block_data.flags &= !NodeBlockFlags::DeferRepackNametable;

        Ok(NodeBlock::new(block_data))
    }

    pub async fn convert_block_v0(
        repository: Arc<RepositoryContext>,
        state: &State,
        block_data_old: Box<NodeBlockDataV0>,
    ) -> Result<(Box<NodeBlockData>, BytesMut), StateError> {
        const EXPECTED_NAME_LENGTH: usize = 16;
        let mut block_data = NodeBlockData::new_from_heap_zeroed();
        let mut name_buffer =
            BytesMut::with_capacity(EXPECTED_NAME_LENGTH * node::BLOCK_V0_NODE_COUNT);

        block_data.flags = block_data_old.flags | NodeBlockFlags::UpgradeGeneratedNametable;
        block_data.node_count = block_data_old.node_count;
        block_data.node_unused_count = block_data_old.node_unused_count;
        block_data.node_unused = block_data_old.node_unused;
        block_data.block_unused_next = block_data_old.block_unused_next;
        block_data.version = NodeBlockFormat::Nametable as u32;

        for (index, node_old) in block_data_old.node.iter().enumerate() {
            let node = &mut block_data.node[index];
            node.flags = node_old.flags;
            node.mode = node_old.mode;
            node.child = node_old.child_mtime_node;
            node.parent = node_old.parent;
            node.sibling = node_old.sibling;
            node.size = node_old.size;
            node.address = node_old.address;

            let name = if !node_old.has_external_name() {
                let slice = unsafe {
                    std::slice::from_raw_parts(
                        node_old.name_string.as_ptr(),
                        node_old.name_string[NODE_NAME_LIMIT] as usize,
                    )
                };

                std::str::from_utf8(slice)
                    .internal("Invalid UTF-8 string")?
                    .to_string()
            } else {
                let name_table = state.nametable(repository.clone()).await?;

                let case_hash =
                    u64::from_le_bytes(node_old.name_string[0..8].try_into().unwrap_or_default());
                let name_string = name_table.load(case_hash);
                if !name_string.is_empty() {
                    name_string.to_string()
                } else {
                    name_table.load(node_old.name_hash).to_string()
                }
            };

            node.name_offset = name_buffer.len() as u32;
            node.name_length = name.len() as u32;
            node.name_hash = hash::hash_string(name.as_str());

            name_buffer.extend_from_slice(name.as_bytes());
        }

        Ok((block_data, name_buffer))
    }

    pub fn convert_block_v2(
        _repository: Arc<RepositoryContext>,
        block_data_v2: Box<NodeBlockDataV2>,
    ) -> Result<Box<NodeBlockData>, StateError> {
        let mut block_data = NodeBlockData::new_from_heap_zeroed();

        block_data.flags = block_data_v2.flags;
        block_data.node_count = block_data_v2.node_count;
        block_data.node_unused_count = block_data_v2.node_unused_count;
        block_data.node_unused = block_data_v2.node_unused;
        block_data.block_unused_next = block_data_v2.block_unused_next;
        block_data.name_table = block_data_v2.name_table;
        block_data.version = NodeBlockFormat::Nametable as u32;

        for (index, node_v2) in block_data_v2.node.iter().enumerate() {
            let node = &mut block_data.node[index];
            node.flags = 0;
            if node_v2.flags & NodeFlagsV2::File != 0 {
                node.flags |= NodeFlags::File;
            }
            if node_v2.flags & NodeFlagsV2::Link != 0 {
                node.flags |= NodeFlags::Link;
            }
            if node_v2.flags & NodeFlagsV2::Discarded != 0 {
                node.flags |= NodeFlags::Discarded;
            }
            if node_v2.flags & NodeFlagsV2::Dirty != 0 {
                node.flags |= NodeFlags::Dirty;
            }
            // NodeV1 staged bits
            // const StagedBits = 0b111111111110000;
            // NodeV2 staged bits
            // const StagedBits = 0b111111111110000000000000000;
            node.flags |= ((node_v2.flags & NodeFlagsV2::StagedBits) >> 12) as u16;
            if node_v2.flags & NodeFlagsV2::Executable != 0 {
                // Executable bit
                node.mode |= 0b1;
            }
            if node_v2.flags & NodeFlagsV2::File != 0 {
                node.child = 0;
            } else {
                node.child = node_v2.child;
            }
            node.parent = node_v2.parent;
            node.sibling = node_v2.sibling;
            node.size = node_v2.size;
            node.address = node_v2.address;
            node.name_offset = node_v2.name_offset;
            node.name_length = node_v2.name_length;
            node.name_hash = node_v2.name_hash;
        }

        Ok(block_data)
    }
}

impl NodeBlockReader<'_> {
    pub fn raw(&self) -> &NodeBlockData {
        self.lock.data.as_ref()
    }

    pub fn node_count(&self) -> usize {
        self.lock.data.node_count as usize
    }

    /// Get the node for the given node index
    pub fn node(&self, node_index: usize) -> &Node {
        debug_assert!(node_index < BLOCK_NODE_COUNT);
        &self.lock.data.node[node_index]
    }

    pub fn clone_name_table(&self) -> Bytes {
        self.lock.name.clone().freeze()
    }

    /// Access the full node block
    pub fn node_block(&self) -> &NodeBlockData {
        &self.lock.data
    }

    /// Check if block is full
    pub fn is_full(&self) -> bool {
        self.lock.data.node_unused_count == 0
            && self.lock.data.node_count == BLOCK_NODE_COUNT as u32
    }

    pub fn is_node_in_use(&self, node_index: usize) -> bool {
        if node_index >= self.lock.data.node_count as usize {
            return false;
        }

        // Check if one of the unused nodes
        let mut unused_count = self.lock.data.node_unused_count;
        let mut unused = self.lock.data.node_unused;
        while unused != INVALID_NODE && unused_count > 0 {
            let unused_index = Node::index(unused);
            if unused_index == node_index {
                return false;
            }
            unused = self.lock.data.node[unused_index].sibling;
            unused_count -= 1;
        }

        true
    }
}

impl NodeBlockWriter<'_> {
    pub fn node_count(&self) -> usize {
        self.lock.data.node_count as usize
    }

    /// Get mutable reference to node for the given node index
    pub fn node(&mut self, node_index: usize) -> &mut Node {
        debug_assert!(node_index < BLOCK_NODE_COUNT);
        &mut self.lock.data.node[node_index]
    }

    /// Mark the block as dirty
    pub fn mark_dirty(&mut self) -> bool {
        let block = &mut self.lock.data;
        let was_dirty = block.flags & NodeBlockFlags::Dirty != 0;
        block.flags |= NodeBlockFlags::Dirty;
        !was_dirty
    }

    pub fn discard_node(&mut self, block_index: usize, node_index: usize) {
        let block = &mut self.lock.data;
        if block.node_unused_count == 0 && block.node_count == BLOCK_NODE_COUNT as u32 {
            block.flags |= NodeBlockFlags::FirstUnusedNode;
        }
        {
            let node = &mut block.node[node_index];
            node.child = 0;
            node.address = Address::default();
            node.flags = NodeFlags::Discarded.bits();
            node.sibling = if block.node_unused_count > 0 {
                block.node_unused
            } else {
                INVALID_NODE
            };
        }
        block.node_unused = node_index as u32;
        block.node_unused_count += 1;
        // Keep the name for the discarded node for history weaving
        block.flags |= NodeBlockFlags::DeferRepackNametable;

        // First block root node is never counted as used in order to let that block reset
        // when all other nodes are unused.
        let node_used_count = block.node_count - if block_index == 0 { 1 } else { 0 };
        if node_used_count == block.node_unused_count {
            block.node_unused = 0;
            block.node_unused_count = 0;
            block.node_count = if block_index == 0 { 1 } else { 0 };
        }
    }

    /// Next unused block index
    pub fn grab_node_unused(&mut self, block_index: u32) -> u32 {
        let block = &mut self.lock.data;
        if block.node_unused_count > 0 {
            let node_index = Node::index(block.node_unused);
            let node = (block_index << BLOCK_NODE_SHIFT) | (node_index as u32);
            lore_trace!("Grab unused node {node_index} from block {block_index}");
            block.node_unused = block.node[node_index].sibling;
            block.node_unused_count -= 1;
            block.node[node_index].zero();
            node
        } else if block.node_count < BLOCK_NODE_COUNT as u32 {
            let node_index = block.node_count as usize;
            let node = (block_index << BLOCK_NODE_SHIFT) | (node_index as u32);
            lore_trace!("Grab uninitialized node {node_index} from block {block_index}");
            block.node_count += 1;
            block.node[node_index].zero();
            node
        } else {
            INVALID_NODE
        }
    }

    /// Get next block with unused nodes
    pub fn block_unused_next(&self) -> u32 {
        self.lock.data.block_unused_next
    }

    /// Check if block is full
    pub fn is_full(&self) -> bool {
        self.lock.data.node_unused_count == 0
            && self.lock.data.node_count == BLOCK_NODE_COUNT as u32
    }

    /// Access the full node block
    pub fn node_block(&mut self) -> &mut NodeBlockData {
        self.lock.data.as_mut()
    }

    pub fn node_name_store(
        &mut self,
        name: &str,
        prev_offset: u32,
        prev_length: u32,
    ) -> Result<(u32, u32), NodeNameError> {
        let prev_offset = prev_offset as usize;
        let prev_length = prev_length as usize;
        if name.len() <= prev_length && (prev_offset + prev_length) < self.lock.name.len() {
            // Safety: With the range check above this is safe, the buffer is guaranteed
            //         to have enough space for the memory copy
            unsafe {
                let offset = prev_offset as isize;
                std::ptr::copy_nonoverlapping(
                    name.as_ptr(),
                    self.lock.name.as_mut_ptr().offset(offset),
                    name.len(),
                );
            };
            Ok((prev_offset as u32, name.len() as u32))
        } else {
            let new_len = self.lock.name.len().saturating_add(name.len());
            if new_len > NODE_NAME_MAX_SIZE {
                return Err(NodeNameError::from(Oversized {
                    context: format!(
                        "node name store would grow to {new_len} bytes, exceeds \
                         NODE_NAME_MAX_SIZE {NODE_NAME_MAX_SIZE}"
                    ),
                }));
            }
            let offset = self.lock.name.len() as u32;
            self.lock.name.extend_from_slice(name.as_bytes());
            self.lock.data.flags |= NodeBlockFlags::RepackNametable;
            Ok((offset, name.len() as u32))
        }
    }

    pub fn node_name_repack(&mut self) {
        let lock = &mut self.lock;
        if lock.data.flags & NodeBlockFlags::RepackNametable == 0
            || lock.data.flags & NodeBlockFlags::DeferRepackNametable != 0
        {
            return;
        }

        let old_len = lock.name.len();
        if lock.name.is_empty() {
            return;
        }
        let mut new_name = BytesMut::with_capacity(lock.name.capacity());

        let node_count = lock.data.node_count as usize;
        for node_index in 0..node_count {
            let (offset, length) = {
                let node = &lock.data.node[node_index];
                if node.flags & NodeFlags::Discarded != 0 {
                    continue;
                }
                (node.name_offset as usize, node.name_length as usize)
            };

            if old_len >= (offset + length) {
                lock.data.node[node_index].name_offset = new_name.len() as u32;

                let name =
                    unsafe { std::str::from_utf8_unchecked(&lock.name[offset..(offset + length)]) };
                new_name.extend_from_slice(name.as_bytes());
            }
        }

        lock.name = new_name;
        lock.data.flags |= NodeBlockFlags::Dirty;
        lock.data.flags &= !NodeBlockFlags::RepackNametable;
    }
}

#[repr(C)]
#[derive(Debug, Clone, Copy, Default, FromBytes, IntoBytes, Immutable)]
pub struct NodeLink {
    /// Node identifier
    pub node: NodeID,
    /// Repository
    pub repository: RepositoryId,
    /// Revision signature
    pub revision: Hash,
}

impl NodeLink {
    pub fn is_valid(&self) -> bool {
        self.node.is_valid_node_id()
    }

    pub fn is_valid_or_root(&self) -> bool {
        self.node == ROOT_NODE || self.node.is_valid_node_id()
    }

    pub fn invalid() -> Self {
        NodeLink {
            node: INVALID_NODE,
            ..Default::default()
        }
    }

    pub async fn resolve(
        &self,
        repository: Arc<RepositoryContext>,
        state: Arc<State>,
    ) -> Result<(Arc<RepositoryContext>, Arc<State>), StateError> {
        if self.is_valid_or_root()
            && (repository.id != self.repository || state.revision() != self.revision)
        {
            let repository = Arc::new(repository.to_link_context(self.repository).await);
            let state = State::deserialize(repository.clone(), self.revision).await?;
            Ok((repository, state))
        } else {
            Ok((repository, state))
        }
    }
}

/// Delta entry
#[repr(C)]
#[derive(Debug, Clone, Copy, Default, IntoBytes, FromBytes, Immutable)]
pub struct NodeDelta {
    /// Node identifier
    pub node: NodeID,
    /// Unused
    pub _unused: u32,
    /// File action
    pub action: u16,
    /// Change flags
    pub flags: u16,
}

impl NodeDelta {
    pub fn from_node_and_flags(node: NodeID, node_flags: u16) -> Self {
        let mut change_flags = change::Flags::None;
        if node_flags & NodeFlags::StagedModify == NodeFlags::StagedModify {
            change_flags |= change::Flags::Modify;
        }
        if node_flags & NodeFlags::StagedMerge == NodeFlags::StagedMerge {
            change_flags |= change::Flags::Merge;
        }

        NodeDelta {
            node,
            _unused: 0,
            action: change::FileAction::from_node_flags(node_flags) as u16,
            flags: change_flags.bits(),
        }
    }

    pub fn from_node_change(change: NodeChange) -> Self {
        let node = match change.action {
            FileAction::Delete => change.from.node,
            FileAction::Add | FileAction::Move | FileAction::Copy | FileAction::Keep => {
                change.to.node
            }
        };
        NodeDelta {
            node,
            _unused: 0,
            action: change.action as u16,
            flags: change.flags.bits(),
        }
    }
}

/// File metadata for a node, 128 bytes
#[repr(C)]
#[derive(Clone, Copy, Debug, IntoBytes, FromBytes, Immutable)]
pub struct NodeFileMetadata {
    /// Custom metadata blob
    pub metadata: Hash,
    /// Repository ID in the cases where the file link can be from an external repository.
    /// For copy/move this is the repository for first revision
    /// For merge this is the repository for second revision
    pub repository: RepositoryId,
    /// Revision signatures
    pub revision: [Hash; 2],
    /// Node index in revision tree
    pub node: [u32; 2],
    /// File action type (copy/move/merge/add/delete/modify)
    pub action: [u16; 2],
    /// Additional flags
    pub flags: [u16; 2],
}

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NodeFileMetadataFlags: u16 {
        /// No flags
        const NoFlag = 0;
    }
}
bitflagsops!(NodeFileMetadataFlags, u16);

bitflags! {
    #[repr(transparent)]
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct NodeFileMetadataBlockFlags: u32 {
        /// Node block is dirty
        const Dirty = 0b1;
    }
}
bitflagsops!(NodeFileMetadataBlockFlags, u32);

impl NodeFileMetadata {
    const fn index_clamp(index: u32) -> u32 {
        if index < BLOCK_NODE_FILE_METADATA_COUNT as u32 {
            index
        } else {
            0
        }
    }

    /// Get the node index from a full node ID
    pub fn index(node: NodeID) -> usize {
        Self::index_clamp(node & NODE_INDEX_MASK) as usize
    }
}

pub const BLOCK_NODE_FILE_METADATA_COUNT: usize = BLOCK_NODE_COUNT;

/// Old block count before the metadata block was extended to 512 elements
const BLOCK_NODE_FILE_METADATA_COUNT_V0: usize = 511;

/// Block of file metadata, 65568 bytes, 32 bytes metadata, 512 blocks of 128 bytes each
#[repr(C)]
#[derive(Clone, Copy, IntoBytes, FromBytes, Immutable)]
pub struct NodeFileMetadataBlockData {
    /// Block flags
    pub flags: u32,
    /// Data format version
    pub version: u32,
    /// Reserved for future extensions, must be zero
    _reserved: [u32; 6],
    /// Node data
    pub node: [NodeFileMetadata; BLOCK_NODE_FILE_METADATA_COUNT],
}

impl ReadBoxFromImmutable for NodeFileMetadataBlockData {}
impl ZeroHeapAlloc for NodeFileMetadataBlockData {}

/// Legacy block of file metadata with 511 elements (old format before extension to 512)
#[repr(C)]
#[derive(Clone, Copy, IntoBytes, FromBytes, Immutable)]
struct NodeFileMetadataBlockDataV0 {
    flags: u32,
    version: u32,
    _reserved: [u32; 6],
    node: [NodeFileMetadata; BLOCK_NODE_FILE_METADATA_COUNT_V0],
}

impl ReadBoxFromImmutable for NodeFileMetadataBlockDataV0 {}
impl ZeroHeapAlloc for NodeFileMetadataBlockDataV0 {}

impl NodeFileMetadataBlockDataV0 {
    /// Convert the old 511-element block into the current 512-element format.
    /// The last element is zero-initialized.
    fn into_current(self) -> Box<NodeFileMetadataBlockData> {
        let mut block = NodeFileMetadataBlockData::new_from_heap_zeroed();
        block.flags = self.flags;
        block.version = self.version;
        block.node[..BLOCK_NODE_FILE_METADATA_COUNT_V0].copy_from_slice(&self.node);
        block
    }
}

impl NodeFileMetadataBlockData {
    /// Read from immutable store with fallback for legacy 511-element blocks.
    pub async fn read_box_from_immutable_compat(
        repository: Arc<RepositoryContext>,
        address: Address,
        cache: bool,
    ) -> Result<Box<NodeFileMetadataBlockData>, ImmutableError> {
        match NodeFileMetadataBlockData::read_box_from_immutable(repository.clone(), address, cache)
            .await
        {
            Ok(block) => Ok(block),
            Err(original_err) if original_err.is_internal() => {
                match NodeFileMetadataBlockDataV0::read_box_from_immutable(
                    repository, address, cache,
                )
                .await
                {
                    Ok(old_block) => Ok(old_block.into_current()),
                    Err(_) => Err(original_err),
                }
            }
            Err(e) => Err(e),
        }
    }
}

/// Internally mutable wrapper around a block of nodes
pub struct NodeFileMetadataBlock {
    /// Node block data containing all the nodes
    data: parking_lot::RwLock<Box<NodeFileMetadataBlockData>>,
}

/// Read accessor for a node block
pub struct NodeFileMetadataBlockReader<'a> {
    lock: RwLockReadGuard<'a, Box<NodeFileMetadataBlockData>>,
}

/// Write accessor for a node block
pub struct NodeFileMetadataBlockWriter<'a> {
    lock: RwLockWriteGuard<'a, Box<NodeFileMetadataBlockData>>,
}

impl Default for NodeFileMetadataBlock {
    fn default() -> Self {
        Self::new(NodeFileMetadataBlockData::new_from_heap_zeroed())
    }
}

impl NodeFileMetadataBlock {
    pub fn new(data: Box<NodeFileMetadataBlockData>) -> Self {
        NodeFileMetadataBlock {
            data: RwLock::new(data),
        }
    }

    /// Get the block index from a full node ID
    pub fn index(node: NodeID) -> usize {
        (node >> BLOCK_NODE_SHIFT) as usize
    }

    pub fn read(&self) -> NodeFileMetadataBlockReader<'_> {
        NodeFileMetadataBlockReader {
            lock: self.data.read(),
        }
    }

    pub fn write(&self) -> NodeFileMetadataBlockWriter<'_> {
        NodeFileMetadataBlockWriter {
            lock: self.data.write(),
        }
    }

    pub fn node(&self, node_index: usize) -> NodeFileMetadata {
        *self.read().node(node_index)
    }
}

impl NodeFileMetadataBlockReader<'_> {
    /// Get the node for the given node index
    pub fn node(&self, node_index: usize) -> &NodeFileMetadata {
        debug_assert!(node_index < BLOCK_NODE_COUNT);
        &self.lock.node[node_index]
    }

    /// Access the full node block
    pub fn node_block(&self) -> &NodeFileMetadataBlockData {
        &self.lock
    }
}

impl NodeFileMetadataBlockWriter<'_> {
    /// Get the node for the given node index
    pub fn node(&mut self, node_index: usize) -> &mut NodeFileMetadata {
        debug_assert!(node_index < BLOCK_NODE_COUNT);
        &mut self.lock.node[node_index]
    }

    /// Mark the block as dirty
    pub fn mark_dirty(&mut self) -> bool {
        let was_dirty = self.lock.flags & NodeFileMetadataBlockFlags::Dirty != 0;
        self.lock.flags |= NodeFileMetadataBlockFlags::Dirty;
        !was_dirty
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node_with_flags(flags: u16) -> Node {
        Node {
            flags,
            ..Default::default()
        }
    }

    #[test]
    fn dirty_flag_bit_positions() {
        // V1: Dirty at bit 3
        assert_eq!(NodeFlags::Dirty.bits(), 0b1000);
        // V1: Dirty does not overlap with Staged (bit 4)
        assert_eq!(NodeFlags::Dirty.bits() & NodeFlags::Staged.bits(), 0);
        // V1: Dirty does not overlap with File/Module/ExternalName
        assert_eq!(NodeFlags::Dirty.bits() & NodeFlags::File.bits(), 0);
        assert_eq!(NodeFlags::Dirty.bits() & NodeFlags::Link.bits(), 0);

        // V2: Dirty at bit 15
        assert_eq!(NodeFlagsV2::Dirty.bits(), 1 << 15);
        // V2: Dirty does not overlap with Staged (bit 16)
        assert_eq!(NodeFlagsV2::Dirty.bits() & NodeFlagsV2::Staged.bits(), 0);
    }

    #[test]
    fn dirty_compound_flags_v1() {
        assert_eq!(
            NodeFlags::DirtyModify.bits(),
            NodeFlags::Dirty.bits() | NodeFlags::StagedModify.bits() & NodeFlags::ActionBits.bits()
        );
        assert_eq!(
            NodeFlags::DirtyAdd.bits(),
            NodeFlags::Dirty.bits() | NodeFlags::StagedAdd.bits() & NodeFlags::ActionBits.bits()
        );
        assert_eq!(
            NodeFlags::DirtyDelete.bits(),
            NodeFlags::Dirty.bits() | NodeFlags::StagedDelete.bits() & NodeFlags::ActionBits.bits()
        );
        assert_eq!(
            NodeFlags::DirtyMove.bits(),
            NodeFlags::Dirty.bits() | NodeFlags::StagedMove.bits() & NodeFlags::ActionBits.bits()
        );
        assert_eq!(
            NodeFlags::DirtyCopy.bits(),
            NodeFlags::Dirty.bits() | NodeFlags::StagedCopy.bits() & NodeFlags::ActionBits.bits()
        );
    }

    #[test]
    fn dirty_bits_mask() {
        // DirtyBits = Dirty + ActionBits (bits 3, 5-9)
        let expected = NodeFlags::Dirty.bits() | NodeFlags::ActionBits.bits();
        assert_eq!(NodeFlags::DirtyBits.bits(), expected);
        // DirtyBits does NOT include Staged (bit 4)
        assert_eq!(NodeFlags::DirtyBits.bits() & NodeFlags::Staged.bits(), 0);
        // DirtyBits does NOT include MergeBits
        assert_eq!(NodeFlags::DirtyBits.bits() & NodeFlags::MergeBits.bits(), 0);
    }

    #[test]
    fn action_bits_mask() {
        // ActionBits = bits 5-9 (shared between Dirty and Staged)
        let expected = (NodeFlags::StagedModify.bits()
            | NodeFlags::StagedAdd.bits()
            | NodeFlags::StagedDelete.bits()
            | NodeFlags::StagedMove.bits()
            | NodeFlags::StagedCopy.bits())
            & !NodeFlags::Staged.bits();
        assert_eq!(NodeFlags::ActionBits.bits(), expected);
    }

    #[test]
    fn node_is_dirty_queries() {
        // Clean node
        let node = Node::default();
        assert!(!node.is_dirty());
        assert!(!node.is_dirty_modify());

        // Dirty only
        let node = node_with_flags(NodeFlags::DirtyModify.bits());
        assert!(node.is_dirty());
        assert!(node.is_dirty_modify());
        assert!(!node.is_dirty_add());
        assert!(!node.is_staged());

        // Dirty+Staged (orthogonal)
        let node = node_with_flags(NodeFlags::Dirty.bits() | NodeFlags::StagedModify.bits());
        assert!(node.is_dirty());
        assert!(node.is_staged());
        assert!(node.is_staged_modify());
        assert!(node.is_dirty_or_staged());
    }

    #[test]
    fn node_has_any_change_flags() {
        assert!(!Node::default().has_any_change_flags());
        assert!(node_with_flags(NodeFlags::Dirty.bits()).has_any_change_flags());
        assert!(node_with_flags(NodeFlags::Staged.bits()).has_any_change_flags());
        assert!(!node_with_flags(NodeFlags::File.bits()).has_any_change_flags());
    }

    #[test]
    fn clear_staged_flags_preserves_dirty() {
        let mut node = node_with_flags(NodeFlags::Dirty.bits() | NodeFlags::StagedModify.bits());
        node.clear_staged_flags();
        assert!(node.is_dirty());
        assert!(!node.is_staged());
        assert_ne!(node.flags & NodeFlags::ActionBits.bits(), 0);
    }

    #[test]
    fn clear_staged_flags_clears_action_when_no_dirty() {
        let mut node = node_with_flags(NodeFlags::StagedModify.bits());
        node.clear_staged_flags();
        assert_eq!(
            node.flags & (NodeFlags::StagedBits.bits() | NodeFlags::Dirty.bits()),
            0
        );
    }

    #[test]
    fn clear_dirty_flags_preserves_staged() {
        let mut node = node_with_flags(NodeFlags::Dirty.bits() | NodeFlags::StagedModify.bits());
        node.clear_dirty_flags();
        assert!(!node.is_dirty());
        assert!(node.is_staged());
        assert!(node.is_staged_modify());
    }

    #[test]
    fn clear_dirty_flags_clears_action_when_no_staged() {
        let mut node = node_with_flags(NodeFlags::DirtyModify.bits());
        node.clear_dirty_flags();
        assert_eq!(
            node.flags & (NodeFlags::DirtyBits.bits() | NodeFlags::StagedBits.bits()),
            0
        );
    }

    #[test]
    fn clear_all_change_flags() {
        let mut node = node_with_flags(
            NodeFlags::File.bits() | NodeFlags::Dirty.bits() | NodeFlags::StagedModify.bits(),
        );
        node.clear_all_change_flags();
        assert!(node.is_file());
        assert!(!node.is_dirty());
        assert!(!node.is_staged());
        assert_eq!(node.flags & NodeFlags::ActionBits.bits(), 0);
    }

    #[test]
    fn action_bits_extraction() {
        let node = node_with_flags(NodeFlags::DirtyMove.bits());
        assert_eq!(
            node.action_bits(),
            NodeFlags::StagedMove.bits() & NodeFlags::ActionBits.bits()
        );
    }
}
